export const AnswerActionTypes = {
    GET_ANSWERS: "GET_ANSWERS",
    UPDATE_ANSWER: "UPDATE_ANSWER",
    ADD_ANSWER: "ADD_ANSWER",
    DELETE_ANSWER: "DELETE_ANSWER",
    ANSWER_ERROR: "ANSWER_ERROR"
}