export const AuthActionTypes = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    USER_LOADED: 'USER_LOADED',
    AUTH_ERROR: 'AUTH_ERROR',
    USER_IMAGE_UPDATED: "USER_IMAGE_UPDATED",
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    USER_ERROR: "USER_ERROR",
    GET_USER_BY_ID: "GET_USER_BY_ID"
    }