export const QuestionActionTypes = {
    GET_QUESTIONS: 'GET_QUESTIONS',
    GET_QUESTION: 'GET_QUESTION',
    QUESTION_ERROR: 'QUESTION_ERROR',
    LIKE_QUESTION: 'LIKE_QUESTION',
    DELETE_QUESTION: 'DELETE_QUESTION',
    ADD_QUESTION: 'ADD_QUESTION',
    UPDATE_QUESTION: "UPDATE_QUESTION",
    GET_USER_QUESTIONS: "GET_USER_QUESTIONS"
    }